# Generated by Django 4.0.6 on 2022-09-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=128, verbose_name='本文'),
        ),
    ]
