# Generated by Django 4.0.6 on 2022-09-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_alter_comment_text'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='snippet',
            table='snippets',
        ),
    ]
