# Generated by Django 4.0.6 on 2022-09-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_card_alter_snippet_description_alter_comment_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='Draft'),
        ),
    ]
